task 1

diff --git a/web_server/1-install_nginx_web_server b/web_server/1-install_nginx_web_server
--- a/web_server/1-install_nginx_web_server
+++ b/web_server/1-install_nginx_web_server
@@ -4,4 +4,7 @@
 sudo apt-get -y update
 sudo apt-get -y install nginx
 echo 'Holberton School' > /var/www/html/index.nginx-debian.html
+echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
+curl -sS http://localhost/ | grep -q "Holberton School" && echo "Test Passed" || echo "Test Failed"
+echo "Holberton School" | sudo tee /var/www/html/index.html
 sudo service nginx start
